### PR TITLE
Rename the Julia package from "ThinkJulia" to "JuliaIntroBR"

### PR DESCRIPTION
**Pull request by chrisvwx**
This PR renames the underlying Julia package from "ThinkJulia" to "JuliaIntroBR".   If you want to change this to "JuliaIntroPTBR" or something else that's fine and I can make the change (we'd also change the github repo name to match).  Unfortunately "JuliaIntroPT-BR" is not a valid name for a Julia module (or package).

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Perhaps we should use the name "Pense em Julia" in accordance with "Pense em Python": https://penseallen.github.io/PensePython2e/

**Comment by chrisvwx** [comment]
I guess that you are not just suggesting naming the package "PenseEmJulia"  rather also naming the book "Pense em Julia: ..."   Is that right?  
See also issue #3

**Comment by abelsiqueira** [comment]
Thanks for this. I've rebased the branch manually. Sorry for taking too long.

**Comment by chrisvwx** [comment]
Thanks!

**Pull request merged**
